# -*- coding: utf-8 -*-
"""Problem01_Week01_Test_Morgan

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gllwMj91dmrk_FL2X_QkU8oz_WvphaUs

#Problem 1

Assume s is a string of lower case characters.

Write a program that counts up the number of vowels contained in the string s. Valid vowels are: 'a', 'e', 'i', 'o', and 'u'. For example, if s = 'azcbobobegghakl', your program should print:

Number of vowels: 5

# Solution
"""

s = 'azcbobobegghakl'
numvowels=0
for iteration in range(len(s)):
  if s[iteration] == 'a' or s[iteration] == 'i'or s[iteration] == 'o' or s[iteration] == 'e' or s[iteration] == 'u':
    numvowels=numvowels+1
print('Number of vowels:',numvowels)

s = 'azcbobobegghakl'
vowels = 'aeiou'
numvowels = 0
for letter in s:
   if letter in vowels:
    numvowels += 1
print('Number of vowels is:', numvowels)

"""# Check"""

def NumberVowelsFunction(s):
  # Paste your code into this box to test
  # Defines your code as a function so it can be used within a checking function
 
  vowels = 'aeiou'
  numvowels = 0
  for letter in s:
    if letter in vowels:
      numvowels += 1
  return numvowels

def Check(s, expected):
  # The checking function used to test the user's function in NumberVowelsFunction
  """
  Compares the output of the user's function NumberVowelsFunction to the expected output "expected"
  """

  print('s = ', s)
  numvowels = NumberVowelsFunction(s)
  print('Number of vowels is:', numvowels)
  if numvowels == expected:
    print('Correct')
    return True
  else:
    #NumberVowelsFunction(s)
    print('Your output:', numvowels)
    print('Expected is:', expected)
    return False

# This section runs your function through Check using a dictionary of s values
# You can use Check by itself to validate your code or you can use the following to check it many times

s = {'azcbobobegghakl': 5, 'ykkfedxsvtwpstpniyeiupst': 5, 'joaketelunuevidbweikceh': 11, 'gijgbtlfyqyeclbboh': 3}

for key in s.keys():
  if Check(key, s[key]):
    print(True)